/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppContratosIndexRouteImport } from './routes/_app/contratos/index'
import { Route as AppProspectosIndexRouteImport } from './routes/_app/prospectos/index'
import { Route as AppProspectosNuevoRouteImport } from './routes/_app/prospectos/nuevo'
import { Route as AppSeguimientoIndexRouteImport } from './routes/_app/seguimiento/index'
import { Route as AppTareasIndexRouteImport } from './routes/_app/tareas/index'
import { Route as AppTrabajosIndexRouteImport } from './routes/_app/trabajos/index'
import { Route as AppTrabajosIdRouteImport } from './routes/_app/trabajos/$id'
import { Route as AppProspectosIdIndexRouteImport } from './routes/_app/prospectos/$id/index'
import { Route as AppProspectosIdConvertirRouteImport } from './routes/_app/prospectos/$id/convertir'
import { Route as AppProspectosIdEditarRouteImport } from './routes/_app/prospectos/$id/editar'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosIndexRoute = AppContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectosIndexRoute = AppProspectosIndexRouteImport.update({
  id: '/prospectos/',
  path: '/prospectos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectosNuevoRoute = AppProspectosNuevoRouteImport.update({
  id: '/prospectos/nuevo',
  path: '/prospectos/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppSeguimientoIndexRoute = AppSeguimientoIndexRouteImport.update({
  id: '/seguimiento/',
  path: '/seguimiento/',
  getParentRoute: () => AppRoute,
} as any)
const AppTareasIndexRoute = AppTareasIndexRouteImport.update({
  id: '/tareas/',
  path: '/tareas/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrabajosIndexRoute = AppTrabajosIndexRouteImport.update({
  id: '/trabajos/',
  path: '/trabajos/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrabajosIdRoute = AppTrabajosIdRouteImport.update({
  id: '/trabajos/$id',
  path: '/trabajos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectosIdIndexRoute = AppProspectosIdIndexRouteImport.update({
  id: '/prospectos/$id/',
  path: '/prospectos/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectosIdConvertirRoute =
  AppProspectosIdConvertirRouteImport.update({
    id: '/prospectos/$id/convertir',
    path: '/prospectos/$id/convertir',
    getParentRoute: () => AppRoute,
  } as any)
const AppProspectosIdEditarRoute = AppProspectosIdEditarRouteImport.update({
  id: '/prospectos/$id/editar',
  path: '/prospectos/$id/editar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/prospectos/nuevo': typeof AppProspectosNuevoRoute
  '/trabajos/$id': typeof AppTrabajosIdRoute
  '/contratos/': typeof AppContratosIndexRoute
  '/prospectos/': typeof AppProspectosIndexRoute
  '/seguimiento/': typeof AppSeguimientoIndexRoute
  '/tareas/': typeof AppTareasIndexRoute
  '/trabajos/': typeof AppTrabajosIndexRoute
  '/prospectos/$id/convertir': typeof AppProspectosIdConvertirRoute
  '/prospectos/$id/editar': typeof AppProspectosIdEditarRoute
  '/prospectos/$id/': typeof AppProspectosIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/': typeof AppIndexRoute
  '/prospectos/nuevo': typeof AppProspectosNuevoRoute
  '/trabajos/$id': typeof AppTrabajosIdRoute
  '/contratos': typeof AppContratosIndexRoute
  '/prospectos': typeof AppProspectosIndexRoute
  '/seguimiento': typeof AppSeguimientoIndexRoute
  '/tareas': typeof AppTareasIndexRoute
  '/trabajos': typeof AppTrabajosIndexRoute
  '/prospectos/$id/convertir': typeof AppProspectosIdConvertirRoute
  '/prospectos/$id/editar': typeof AppProspectosIdEditarRoute
  '/prospectos/$id': typeof AppProspectosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/prospectos/nuevo': typeof AppProspectosNuevoRoute
  '/_app/trabajos/$id': typeof AppTrabajosIdRoute
  '/_app/contratos/': typeof AppContratosIndexRoute
  '/_app/prospectos/': typeof AppProspectosIndexRoute
  '/_app/seguimiento/': typeof AppSeguimientoIndexRoute
  '/_app/tareas/': typeof AppTareasIndexRoute
  '/_app/trabajos/': typeof AppTrabajosIndexRoute
  '/_app/prospectos/$id/convertir': typeof AppProspectosIdConvertirRoute
  '/_app/prospectos/$id/editar': typeof AppProspectosIdEditarRoute
  '/_app/prospectos/$id/': typeof AppProspectosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/prospectos/nuevo'
    | '/trabajos/$id'
    | '/contratos/'
    | '/prospectos/'
    | '/seguimiento/'
    | '/tareas/'
    | '/trabajos/'
    | '/prospectos/$id/convertir'
    | '/prospectos/$id/editar'
    | '/prospectos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/'
    | '/prospectos/nuevo'
    | '/trabajos/$id'
    | '/contratos'
    | '/prospectos'
    | '/seguimiento'
    | '/tareas'
    | '/trabajos'
    | '/prospectos/$id/convertir'
    | '/prospectos/$id/editar'
    | '/prospectos/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$'
    | '/_app/'
    | '/_app/prospectos/nuevo'
    | '/_app/trabajos/$id'
    | '/_app/contratos/'
    | '/_app/prospectos/'
    | '/_app/seguimiento/'
    | '/_app/tareas/'
    | '/_app/trabajos/'
    | '/_app/prospectos/$id/convertir'
    | '/_app/prospectos/$id/editar'
    | '/_app/prospectos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos/': {
      id: '/_app/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AppContratosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospectos/': {
      id: '/_app/prospectos/'
      path: '/prospectos'
      fullPath: '/prospectos/'
      preLoaderRoute: typeof AppProspectosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospectos/nuevo': {
      id: '/_app/prospectos/nuevo'
      path: '/prospectos/nuevo'
      fullPath: '/prospectos/nuevo'
      preLoaderRoute: typeof AppProspectosNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seguimiento/': {
      id: '/_app/seguimiento/'
      path: '/seguimiento'
      fullPath: '/seguimiento/'
      preLoaderRoute: typeof AppSeguimientoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tareas/': {
      id: '/_app/tareas/'
      path: '/tareas'
      fullPath: '/tareas/'
      preLoaderRoute: typeof AppTareasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trabajos/': {
      id: '/_app/trabajos/'
      path: '/trabajos'
      fullPath: '/trabajos/'
      preLoaderRoute: typeof AppTrabajosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trabajos/$id': {
      id: '/_app/trabajos/$id'
      path: '/trabajos/$id'
      fullPath: '/trabajos/$id'
      preLoaderRoute: typeof AppTrabajosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospectos/$id/': {
      id: '/_app/prospectos/$id/'
      path: '/prospectos/$id'
      fullPath: '/prospectos/$id/'
      preLoaderRoute: typeof AppProspectosIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospectos/$id/convertir': {
      id: '/_app/prospectos/$id/convertir'
      path: '/prospectos/$id/convertir'
      fullPath: '/prospectos/$id/convertir'
      preLoaderRoute: typeof AppProspectosIdConvertirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospectos/$id/editar': {
      id: '/_app/prospectos/$id/editar'
      path: '/prospectos/$id/editar'
      fullPath: '/prospectos/$id/editar'
      preLoaderRoute: typeof AppProspectosIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProspectosNuevoRoute: typeof AppProspectosNuevoRoute
  AppTrabajosIdRoute: typeof AppTrabajosIdRoute
  AppContratosIndexRoute: typeof AppContratosIndexRoute
  AppProspectosIndexRoute: typeof AppProspectosIndexRoute
  AppSeguimientoIndexRoute: typeof AppSeguimientoIndexRoute
  AppTareasIndexRoute: typeof AppTareasIndexRoute
  AppTrabajosIndexRoute: typeof AppTrabajosIndexRoute
  AppProspectosIdConvertirRoute: typeof AppProspectosIdConvertirRoute
  AppProspectosIdEditarRoute: typeof AppProspectosIdEditarRoute
  AppProspectosIdIndexRoute: typeof AppProspectosIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppIndexRoute: AppIndexRoute,
  AppProspectosNuevoRoute: AppProspectosNuevoRoute,
  AppTrabajosIdRoute: AppTrabajosIdRoute,
  AppContratosIndexRoute: AppContratosIndexRoute,
  AppProspectosIndexRoute: AppProspectosIndexRoute,
  AppSeguimientoIndexRoute: AppSeguimientoIndexRoute,
  AppTareasIndexRoute: AppTareasIndexRoute,
  AppTrabajosIndexRoute: AppTrabajosIndexRoute,
  AppProspectosIdConvertirRoute: AppProspectosIdConvertirRoute,
  AppProspectosIdEditarRoute: AppProspectosIdEditarRoute,
  AppProspectosIdIndexRoute: AppProspectosIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
