/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ImprimirRouteImport } from './routes/imprimir'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppCuentaRouteImport } from './routes/_app/cuenta'
import { Route as AppAgendaIndexRouteImport } from './routes/_app/agenda/index'
import { Route as AppAuditoriaIndexRouteImport } from './routes/_app/auditoria/index'
import { Route as AppAusenciasIndexRouteImport } from './routes/_app/ausencias/index'
import { Route as AppCalendarioIndexRouteImport } from './routes/_app/calendario/index'
import { Route as AppCatalogosIndexRouteImport } from './routes/_app/catalogos/index'
import { Route as AppClientesIdRouteImport } from './routes/_app/clientes/$id'
import { Route as AppContratosIndexRouteImport } from './routes/_app/contratos/index'
import { Route as AppCotizacionesIndexRouteImport } from './routes/_app/cotizaciones/index'
import { Route as AppDocumentosIndexRouteImport } from './routes/_app/documentos/index'
import { Route as AppEntregablesIndexRouteImport } from './routes/_app/entregables/index'
import { Route as AppHorasExtraIndexRouteImport } from './routes/_app/horas-extra/index'
import { Route as AppModulosIndexRouteImport } from './routes/_app/modulos/index'
import { Route as AppParametrosIndexRouteImport } from './routes/_app/parametros/index'
import { Route as AppProgramacionIndexRouteImport } from './routes/_app/programacion/index'
import { Route as AppProspectosIndexRouteImport } from './routes/_app/prospectos/index'
import { Route as AppProspectosNuevoRouteImport } from './routes/_app/prospectos/nuevo'
import { Route as AppProveedoresIndexRouteImport } from './routes/_app/proveedores/index'
import { Route as AppProveedoresIdRouteImport } from './routes/_app/proveedores/$id'
import { Route as AppReportesIndexRouteImport } from './routes/_app/reportes/index'
import { Route as AppReunionesIndexRouteImport } from './routes/_app/reuniones/index'
import { Route as AppRolesIndexRouteImport } from './routes/_app/roles/index'
import { Route as AppRolesIdRouteImport } from './routes/_app/roles/$id'
import { Route as AppSeguimientoIndexRouteImport } from './routes/_app/seguimiento/index'
import { Route as AppTareasIndexRouteImport } from './routes/_app/tareas/index'
import { Route as AppTrabajosIndexRouteImport } from './routes/_app/trabajos/index'
import { Route as AppTrabajosIdRouteImport } from './routes/_app/trabajos/$id'
import { Route as AppTrabajosClienteDirectoRouteImport } from './routes/_app/trabajos/cliente-directo'
import { Route as AppTrabajosDeProveedorRouteImport } from './routes/_app/trabajos/de-proveedor'
import { Route as AppUsuariosIndexRouteImport } from './routes/_app/usuarios/index'
import { Route as AppUsuariosIdRouteImport } from './routes/_app/usuarios/$id'
import { Route as ImprimirContratoIdRouteImport } from './routes/imprimir/contrato/$id'
import { Route as ImprimirCotizacionIdRouteImport } from './routes/imprimir/cotizacion/$id'
import { Route as ImprimirReciboIdRouteImport } from './routes/imprimir/recibo/$id'
import { Route as AppProspectosIdIndexRouteImport } from './routes/_app/prospectos/$id/index'
import { Route as AppProspectosIdConvertirRouteImport } from './routes/_app/prospectos/$id/convertir'
import { Route as AppProspectosIdEditarRouteImport } from './routes/_app/prospectos/$id/editar'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprimirRoute = ImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppCuentaRoute = AppCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaIndexRoute = AppAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaIndexRoute = AppAuditoriaIndexRouteImport.update({
  id: '/auditoria/',
  path: '/auditoria/',
  getParentRoute: () => AppRoute,
} as any)
const AppAusenciasIndexRoute = AppAusenciasIndexRouteImport.update({
  id: '/ausencias/',
  path: '/ausencias/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioIndexRoute = AppCalendarioIndexRouteImport.update({
  id: '/calendario/',
  path: '/calendario/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogosIndexRoute = AppCatalogosIndexRouteImport.update({
  id: '/catalogos/',
  path: '/catalogos/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosIndexRoute = AppContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => AppRoute,
} as any)
const AppCotizacionesIndexRoute = AppCotizacionesIndexRouteImport.update({
  id: '/cotizaciones/',
  path: '/cotizaciones/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosIndexRoute = AppDocumentosIndexRouteImport.update({
  id: '/documentos/',
  path: '/documentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntregablesIndexRoute = AppEntregablesIndexRouteImport.update({
  id: '/entregables/',
  path: '/entregables/',
  getParentRoute: () => AppRoute,
} as any)
const AppHorasExtraIndexRoute = AppHorasExtraIndexRouteImport.update({
  id: '/horas-extra/',
  path: '/horas-extra/',
  getParentRoute: () => AppRoute,
} as any)
const AppModulosIndexRoute = AppModulosIndexRouteImport.update({
  id: '/modulos/',
  path: '/modulos/',
  getParentRoute: () => AppRoute,
} as any)
const AppParametrosIndexRoute = AppParametrosIndexRouteImport.update({
  id: '/parametros/',
  path: '/parametros/',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramacionIndexRoute = AppProgramacionIndexRouteImport.update({
  id: '/programacion/',
  path: '/programacion/',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectosIndexRoute = AppProspectosIndexRouteImport.update({
  id: '/prospectos/',
  path: '/prospectos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectosNuevoRoute = AppProspectosNuevoRouteImport.update({
  id: '/prospectos/nuevo',
  path: '/prospectos/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppProveedoresIndexRoute = AppProveedoresIndexRouteImport.update({
  id: '/proveedores/',
  path: '/proveedores/',
  getParentRoute: () => AppRoute,
} as any)
const AppProveedoresIdRoute = AppProveedoresIdRouteImport.update({
  id: '/proveedores/$id',
  path: '/proveedores/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportesIndexRoute = AppReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => AppRoute,
} as any)
const AppReunionesIndexRoute = AppReunionesIndexRouteImport.update({
  id: '/reuniones/',
  path: '/reuniones/',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesIdRoute = AppRolesIdRouteImport.update({
  id: '/roles/$id',
  path: '/roles/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSeguimientoIndexRoute = AppSeguimientoIndexRouteImport.update({
  id: '/seguimiento/',
  path: '/seguimiento/',
  getParentRoute: () => AppRoute,
} as any)
const AppTareasIndexRoute = AppTareasIndexRouteImport.update({
  id: '/tareas/',
  path: '/tareas/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrabajosIndexRoute = AppTrabajosIndexRouteImport.update({
  id: '/trabajos/',
  path: '/trabajos/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrabajosIdRoute = AppTrabajosIdRouteImport.update({
  id: '/trabajos/$id',
  path: '/trabajos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTrabajosClienteDirectoRoute =
  AppTrabajosClienteDirectoRouteImport.update({
    id: '/trabajos/cliente-directo',
    path: '/trabajos/cliente-directo',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrabajosDeProveedorRoute = AppTrabajosDeProveedorRouteImport.update({
  id: '/trabajos/de-proveedor',
  path: '/trabajos/de-proveedor',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosIndexRoute = AppUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosIdRoute = AppUsuariosIdRouteImport.update({
  id: '/usuarios/$id',
  path: '/usuarios/$id',
  getParentRoute: () => AppRoute,
} as any)
const ImprimirContratoIdRoute = ImprimirContratoIdRouteImport.update({
  id: '/contrato/$id',
  path: '/contrato/$id',
  getParentRoute: () => ImprimirRoute,
} as any)
const ImprimirCotizacionIdRoute = ImprimirCotizacionIdRouteImport.update({
  id: '/cotizacion/$id',
  path: '/cotizacion/$id',
  getParentRoute: () => ImprimirRoute,
} as any)
const ImprimirReciboIdRoute = ImprimirReciboIdRouteImport.update({
  id: '/recibo/$id',
  path: '/recibo/$id',
  getParentRoute: () => ImprimirRoute,
} as any)
const AppProspectosIdIndexRoute = AppProspectosIdIndexRouteImport.update({
  id: '/prospectos/$id/',
  path: '/prospectos/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppProspectosIdConvertirRoute =
  AppProspectosIdConvertirRouteImport.update({
    id: '/prospectos/$id/convertir',
    path: '/prospectos/$id/convertir',
    getParentRoute: () => AppRoute,
  } as any)
const AppProspectosIdEditarRoute = AppProspectosIdEditarRouteImport.update({
  id: '/prospectos/$id/editar',
  path: '/prospectos/$id/editar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/imprimir': typeof ImprimirRouteWithChildren
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/cuenta': typeof AppCuentaRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/prospectos/nuevo': typeof AppProspectosNuevoRoute
  '/proveedores/$id': typeof AppProveedoresIdRoute
  '/roles/$id': typeof AppRolesIdRoute
  '/trabajos/$id': typeof AppTrabajosIdRoute
  '/trabajos/cliente-directo': typeof AppTrabajosClienteDirectoRoute
  '/trabajos/de-proveedor': typeof AppTrabajosDeProveedorRoute
  '/usuarios/$id': typeof AppUsuariosIdRoute
  '/imprimir/contrato/$id': typeof ImprimirContratoIdRoute
  '/imprimir/cotizacion/$id': typeof ImprimirCotizacionIdRoute
  '/imprimir/recibo/$id': typeof ImprimirReciboIdRoute
  '/agenda/': typeof AppAgendaIndexRoute
  '/auditoria/': typeof AppAuditoriaIndexRoute
  '/ausencias/': typeof AppAusenciasIndexRoute
  '/calendario/': typeof AppCalendarioIndexRoute
  '/catalogos/': typeof AppCatalogosIndexRoute
  '/contratos/': typeof AppContratosIndexRoute
  '/cotizaciones/': typeof AppCotizacionesIndexRoute
  '/documentos/': typeof AppDocumentosIndexRoute
  '/entregables/': typeof AppEntregablesIndexRoute
  '/horas-extra/': typeof AppHorasExtraIndexRoute
  '/modulos/': typeof AppModulosIndexRoute
  '/parametros/': typeof AppParametrosIndexRoute
  '/programacion/': typeof AppProgramacionIndexRoute
  '/prospectos/': typeof AppProspectosIndexRoute
  '/proveedores/': typeof AppProveedoresIndexRoute
  '/reportes/': typeof AppReportesIndexRoute
  '/reuniones/': typeof AppReunionesIndexRoute
  '/roles/': typeof AppRolesIndexRoute
  '/seguimiento/': typeof AppSeguimientoIndexRoute
  '/tareas/': typeof AppTareasIndexRoute
  '/trabajos/': typeof AppTrabajosIndexRoute
  '/usuarios/': typeof AppUsuariosIndexRoute
  '/prospectos/$id/convertir': typeof AppProspectosIdConvertirRoute
  '/prospectos/$id/editar': typeof AppProspectosIdEditarRoute
  '/prospectos/$id/': typeof AppProspectosIdIndexRoute
}
export interface FileRoutesByTo {
  '/imprimir': typeof ImprimirRouteWithChildren
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/cuenta': typeof AppCuentaRoute
  '/': typeof AppIndexRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/prospectos/nuevo': typeof AppProspectosNuevoRoute
  '/proveedores/$id': typeof AppProveedoresIdRoute
  '/roles/$id': typeof AppRolesIdRoute
  '/trabajos/$id': typeof AppTrabajosIdRoute
  '/trabajos/cliente-directo': typeof AppTrabajosClienteDirectoRoute
  '/trabajos/de-proveedor': typeof AppTrabajosDeProveedorRoute
  '/usuarios/$id': typeof AppUsuariosIdRoute
  '/imprimir/contrato/$id': typeof ImprimirContratoIdRoute
  '/imprimir/cotizacion/$id': typeof ImprimirCotizacionIdRoute
  '/imprimir/recibo/$id': typeof ImprimirReciboIdRoute
  '/agenda': typeof AppAgendaIndexRoute
  '/auditoria': typeof AppAuditoriaIndexRoute
  '/ausencias': typeof AppAusenciasIndexRoute
  '/calendario': typeof AppCalendarioIndexRoute
  '/catalogos': typeof AppCatalogosIndexRoute
  '/contratos': typeof AppContratosIndexRoute
  '/cotizaciones': typeof AppCotizacionesIndexRoute
  '/documentos': typeof AppDocumentosIndexRoute
  '/entregables': typeof AppEntregablesIndexRoute
  '/horas-extra': typeof AppHorasExtraIndexRoute
  '/modulos': typeof AppModulosIndexRoute
  '/parametros': typeof AppParametrosIndexRoute
  '/programacion': typeof AppProgramacionIndexRoute
  '/prospectos': typeof AppProspectosIndexRoute
  '/proveedores': typeof AppProveedoresIndexRoute
  '/reportes': typeof AppReportesIndexRoute
  '/reuniones': typeof AppReunionesIndexRoute
  '/roles': typeof AppRolesIndexRoute
  '/seguimiento': typeof AppSeguimientoIndexRoute
  '/tareas': typeof AppTareasIndexRoute
  '/trabajos': typeof AppTrabajosIndexRoute
  '/usuarios': typeof AppUsuariosIndexRoute
  '/prospectos/$id/convertir': typeof AppProspectosIdConvertirRoute
  '/prospectos/$id/editar': typeof AppProspectosIdEditarRoute
  '/prospectos/$id': typeof AppProspectosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/imprimir': typeof ImprimirRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/cuenta': typeof AppCuentaRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/_app/prospectos/nuevo': typeof AppProspectosNuevoRoute
  '/_app/proveedores/$id': typeof AppProveedoresIdRoute
  '/_app/roles/$id': typeof AppRolesIdRoute
  '/_app/trabajos/$id': typeof AppTrabajosIdRoute
  '/_app/trabajos/cliente-directo': typeof AppTrabajosClienteDirectoRoute
  '/_app/trabajos/de-proveedor': typeof AppTrabajosDeProveedorRoute
  '/_app/usuarios/$id': typeof AppUsuariosIdRoute
  '/imprimir/contrato/$id': typeof ImprimirContratoIdRoute
  '/imprimir/cotizacion/$id': typeof ImprimirCotizacionIdRoute
  '/imprimir/recibo/$id': typeof ImprimirReciboIdRoute
  '/_app/agenda/': typeof AppAgendaIndexRoute
  '/_app/auditoria/': typeof AppAuditoriaIndexRoute
  '/_app/ausencias/': typeof AppAusenciasIndexRoute
  '/_app/calendario/': typeof AppCalendarioIndexRoute
  '/_app/catalogos/': typeof AppCatalogosIndexRoute
  '/_app/contratos/': typeof AppContratosIndexRoute
  '/_app/cotizaciones/': typeof AppCotizacionesIndexRoute
  '/_app/documentos/': typeof AppDocumentosIndexRoute
  '/_app/entregables/': typeof AppEntregablesIndexRoute
  '/_app/horas-extra/': typeof AppHorasExtraIndexRoute
  '/_app/modulos/': typeof AppModulosIndexRoute
  '/_app/parametros/': typeof AppParametrosIndexRoute
  '/_app/programacion/': typeof AppProgramacionIndexRoute
  '/_app/prospectos/': typeof AppProspectosIndexRoute
  '/_app/proveedores/': typeof AppProveedoresIndexRoute
  '/_app/reportes/': typeof AppReportesIndexRoute
  '/_app/reuniones/': typeof AppReunionesIndexRoute
  '/_app/roles/': typeof AppRolesIndexRoute
  '/_app/seguimiento/': typeof AppSeguimientoIndexRoute
  '/_app/tareas/': typeof AppTareasIndexRoute
  '/_app/trabajos/': typeof AppTrabajosIndexRoute
  '/_app/usuarios/': typeof AppUsuariosIndexRoute
  '/_app/prospectos/$id/convertir': typeof AppProspectosIdConvertirRoute
  '/_app/prospectos/$id/editar': typeof AppProspectosIdEditarRoute
  '/_app/prospectos/$id/': typeof AppProspectosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imprimir'
    | '/login'
    | '/$'
    | '/cuenta'
    | '/clientes/$id'
    | '/prospectos/nuevo'
    | '/proveedores/$id'
    | '/roles/$id'
    | '/trabajos/$id'
    | '/trabajos/cliente-directo'
    | '/trabajos/de-proveedor'
    | '/usuarios/$id'
    | '/imprimir/contrato/$id'
    | '/imprimir/cotizacion/$id'
    | '/imprimir/recibo/$id'
    | '/agenda/'
    | '/auditoria/'
    | '/ausencias/'
    | '/calendario/'
    | '/catalogos/'
    | '/contratos/'
    | '/cotizaciones/'
    | '/documentos/'
    | '/entregables/'
    | '/horas-extra/'
    | '/modulos/'
    | '/parametros/'
    | '/programacion/'
    | '/prospectos/'
    | '/proveedores/'
    | '/reportes/'
    | '/reuniones/'
    | '/roles/'
    | '/seguimiento/'
    | '/tareas/'
    | '/trabajos/'
    | '/usuarios/'
    | '/prospectos/$id/convertir'
    | '/prospectos/$id/editar'
    | '/prospectos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/imprimir'
    | '/login'
    | '/$'
    | '/cuenta'
    | '/'
    | '/clientes/$id'
    | '/prospectos/nuevo'
    | '/proveedores/$id'
    | '/roles/$id'
    | '/trabajos/$id'
    | '/trabajos/cliente-directo'
    | '/trabajos/de-proveedor'
    | '/usuarios/$id'
    | '/imprimir/contrato/$id'
    | '/imprimir/cotizacion/$id'
    | '/imprimir/recibo/$id'
    | '/agenda'
    | '/auditoria'
    | '/ausencias'
    | '/calendario'
    | '/catalogos'
    | '/contratos'
    | '/cotizaciones'
    | '/documentos'
    | '/entregables'
    | '/horas-extra'
    | '/modulos'
    | '/parametros'
    | '/programacion'
    | '/prospectos'
    | '/proveedores'
    | '/reportes'
    | '/reuniones'
    | '/roles'
    | '/seguimiento'
    | '/tareas'
    | '/trabajos'
    | '/usuarios'
    | '/prospectos/$id/convertir'
    | '/prospectos/$id/editar'
    | '/prospectos/$id'
  id:
    | '__root__'
    | '/_app'
    | '/imprimir'
    | '/login'
    | '/_app/$'
    | '/_app/cuenta'
    | '/_app/'
    | '/_app/clientes/$id'
    | '/_app/prospectos/nuevo'
    | '/_app/proveedores/$id'
    | '/_app/roles/$id'
    | '/_app/trabajos/$id'
    | '/_app/trabajos/cliente-directo'
    | '/_app/trabajos/de-proveedor'
    | '/_app/usuarios/$id'
    | '/imprimir/contrato/$id'
    | '/imprimir/cotizacion/$id'
    | '/imprimir/recibo/$id'
    | '/_app/agenda/'
    | '/_app/auditoria/'
    | '/_app/ausencias/'
    | '/_app/calendario/'
    | '/_app/catalogos/'
    | '/_app/contratos/'
    | '/_app/cotizaciones/'
    | '/_app/documentos/'
    | '/_app/entregables/'
    | '/_app/horas-extra/'
    | '/_app/modulos/'
    | '/_app/parametros/'
    | '/_app/programacion/'
    | '/_app/prospectos/'
    | '/_app/proveedores/'
    | '/_app/reportes/'
    | '/_app/reuniones/'
    | '/_app/roles/'
    | '/_app/seguimiento/'
    | '/_app/tareas/'
    | '/_app/trabajos/'
    | '/_app/usuarios/'
    | '/_app/prospectos/$id/convertir'
    | '/_app/prospectos/$id/editar'
    | '/_app/prospectos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ImprimirRoute: typeof ImprimirRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprimir': {
      id: '/imprimir'
      path: '/imprimir'
      fullPath: '/imprimir'
      preLoaderRoute: typeof ImprimirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cuenta': {
      id: '/_app/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AppCuentaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda/': {
      id: '/_app/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AppAgendaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auditoria/': {
      id: '/_app/auditoria/'
      path: '/auditoria'
      fullPath: '/auditoria/'
      preLoaderRoute: typeof AppAuditoriaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ausencias/': {
      id: '/_app/ausencias/'
      path: '/ausencias'
      fullPath: '/ausencias/'
      preLoaderRoute: typeof AppAusenciasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario/': {
      id: '/_app/calendario/'
      path: '/calendario'
      fullPath: '/calendario/'
      preLoaderRoute: typeof AppCalendarioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogos/': {
      id: '/_app/catalogos/'
      path: '/catalogos'
      fullPath: '/catalogos/'
      preLoaderRoute: typeof AppCatalogosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos/': {
      id: '/_app/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AppContratosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cotizaciones/': {
      id: '/_app/cotizaciones/'
      path: '/cotizaciones'
      fullPath: '/cotizaciones/'
      preLoaderRoute: typeof AppCotizacionesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos/': {
      id: '/_app/documentos/'
      path: '/documentos'
      fullPath: '/documentos/'
      preLoaderRoute: typeof AppDocumentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entregables/': {
      id: '/_app/entregables/'
      path: '/entregables'
      fullPath: '/entregables/'
      preLoaderRoute: typeof AppEntregablesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/horas-extra/': {
      id: '/_app/horas-extra/'
      path: '/horas-extra'
      fullPath: '/horas-extra/'
      preLoaderRoute: typeof AppHorasExtraIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modulos/': {
      id: '/_app/modulos/'
      path: '/modulos'
      fullPath: '/modulos/'
      preLoaderRoute: typeof AppModulosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametros/': {
      id: '/_app/parametros/'
      path: '/parametros'
      fullPath: '/parametros/'
      preLoaderRoute: typeof AppParametrosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacion/': {
      id: '/_app/programacion/'
      path: '/programacion'
      fullPath: '/programacion/'
      preLoaderRoute: typeof AppProgramacionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospectos/': {
      id: '/_app/prospectos/'
      path: '/prospectos'
      fullPath: '/prospectos/'
      preLoaderRoute: typeof AppProspectosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospectos/nuevo': {
      id: '/_app/prospectos/nuevo'
      path: '/prospectos/nuevo'
      fullPath: '/prospectos/nuevo'
      preLoaderRoute: typeof AppProspectosNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proveedores/': {
      id: '/_app/proveedores/'
      path: '/proveedores'
      fullPath: '/proveedores/'
      preLoaderRoute: typeof AppProveedoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proveedores/$id': {
      id: '/_app/proveedores/$id'
      path: '/proveedores/$id'
      fullPath: '/proveedores/$id'
      preLoaderRoute: typeof AppProveedoresIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reportes/': {
      id: '/_app/reportes/'
      path: '/reportes'
      fullPath: '/reportes/'
      preLoaderRoute: typeof AppReportesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reuniones/': {
      id: '/_app/reuniones/'
      path: '/reuniones'
      fullPath: '/reuniones/'
      preLoaderRoute: typeof AppReunionesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles/': {
      id: '/_app/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles/$id': {
      id: '/_app/roles/$id'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof AppRolesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seguimiento/': {
      id: '/_app/seguimiento/'
      path: '/seguimiento'
      fullPath: '/seguimiento/'
      preLoaderRoute: typeof AppSeguimientoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tareas/': {
      id: '/_app/tareas/'
      path: '/tareas'
      fullPath: '/tareas/'
      preLoaderRoute: typeof AppTareasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trabajos/': {
      id: '/_app/trabajos/'
      path: '/trabajos'
      fullPath: '/trabajos/'
      preLoaderRoute: typeof AppTrabajosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trabajos/$id': {
      id: '/_app/trabajos/$id'
      path: '/trabajos/$id'
      fullPath: '/trabajos/$id'
      preLoaderRoute: typeof AppTrabajosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trabajos/cliente-directo': {
      id: '/_app/trabajos/cliente-directo'
      path: '/trabajos/cliente-directo'
      fullPath: '/trabajos/cliente-directo'
      preLoaderRoute: typeof AppTrabajosClienteDirectoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trabajos/de-proveedor': {
      id: '/_app/trabajos/de-proveedor'
      path: '/trabajos/de-proveedor'
      fullPath: '/trabajos/de-proveedor'
      preLoaderRoute: typeof AppTrabajosDeProveedorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios/': {
      id: '/_app/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof AppUsuariosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios/$id': {
      id: '/_app/usuarios/$id'
      path: '/usuarios/$id'
      fullPath: '/usuarios/$id'
      preLoaderRoute: typeof AppUsuariosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/imprimir/contrato/$id': {
      id: '/imprimir/contrato/$id'
      path: '/contrato/$id'
      fullPath: '/imprimir/contrato/$id'
      preLoaderRoute: typeof ImprimirContratoIdRouteImport
      parentRoute: typeof ImprimirRoute
    }
    '/imprimir/cotizacion/$id': {
      id: '/imprimir/cotizacion/$id'
      path: '/cotizacion/$id'
      fullPath: '/imprimir/cotizacion/$id'
      preLoaderRoute: typeof ImprimirCotizacionIdRouteImport
      parentRoute: typeof ImprimirRoute
    }
    '/imprimir/recibo/$id': {
      id: '/imprimir/recibo/$id'
      path: '/recibo/$id'
      fullPath: '/imprimir/recibo/$id'
      preLoaderRoute: typeof ImprimirReciboIdRouteImport
      parentRoute: typeof ImprimirRoute
    }
    '/_app/prospectos/$id/': {
      id: '/_app/prospectos/$id/'
      path: '/prospectos/$id'
      fullPath: '/prospectos/$id/'
      preLoaderRoute: typeof AppProspectosIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospectos/$id/convertir': {
      id: '/_app/prospectos/$id/convertir'
      path: '/prospectos/$id/convertir'
      fullPath: '/prospectos/$id/convertir'
      preLoaderRoute: typeof AppProspectosIdConvertirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospectos/$id/editar': {
      id: '/_app/prospectos/$id/editar'
      path: '/prospectos/$id/editar'
      fullPath: '/prospectos/$id/editar'
      preLoaderRoute: typeof AppProspectosIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppCuentaRoute: typeof AppCuentaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppProspectosNuevoRoute: typeof AppProspectosNuevoRoute
  AppProveedoresIdRoute: typeof AppProveedoresIdRoute
  AppRolesIdRoute: typeof AppRolesIdRoute
  AppTrabajosIdRoute: typeof AppTrabajosIdRoute
  AppTrabajosClienteDirectoRoute: typeof AppTrabajosClienteDirectoRoute
  AppTrabajosDeProveedorRoute: typeof AppTrabajosDeProveedorRoute
  AppUsuariosIdRoute: typeof AppUsuariosIdRoute
  AppAgendaIndexRoute: typeof AppAgendaIndexRoute
  AppAuditoriaIndexRoute: typeof AppAuditoriaIndexRoute
  AppAusenciasIndexRoute: typeof AppAusenciasIndexRoute
  AppCalendarioIndexRoute: typeof AppCalendarioIndexRoute
  AppCatalogosIndexRoute: typeof AppCatalogosIndexRoute
  AppContratosIndexRoute: typeof AppContratosIndexRoute
  AppCotizacionesIndexRoute: typeof AppCotizacionesIndexRoute
  AppDocumentosIndexRoute: typeof AppDocumentosIndexRoute
  AppEntregablesIndexRoute: typeof AppEntregablesIndexRoute
  AppHorasExtraIndexRoute: typeof AppHorasExtraIndexRoute
  AppModulosIndexRoute: typeof AppModulosIndexRoute
  AppParametrosIndexRoute: typeof AppParametrosIndexRoute
  AppProgramacionIndexRoute: typeof AppProgramacionIndexRoute
  AppProspectosIndexRoute: typeof AppProspectosIndexRoute
  AppProveedoresIndexRoute: typeof AppProveedoresIndexRoute
  AppReportesIndexRoute: typeof AppReportesIndexRoute
  AppReunionesIndexRoute: typeof AppReunionesIndexRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
  AppSeguimientoIndexRoute: typeof AppSeguimientoIndexRoute
  AppTareasIndexRoute: typeof AppTareasIndexRoute
  AppTrabajosIndexRoute: typeof AppTrabajosIndexRoute
  AppUsuariosIndexRoute: typeof AppUsuariosIndexRoute
  AppProspectosIdConvertirRoute: typeof AppProspectosIdConvertirRoute
  AppProspectosIdEditarRoute: typeof AppProspectosIdEditarRoute
  AppProspectosIdIndexRoute: typeof AppProspectosIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppCuentaRoute: AppCuentaRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppProspectosNuevoRoute: AppProspectosNuevoRoute,
  AppProveedoresIdRoute: AppProveedoresIdRoute,
  AppRolesIdRoute: AppRolesIdRoute,
  AppTrabajosIdRoute: AppTrabajosIdRoute,
  AppTrabajosClienteDirectoRoute: AppTrabajosClienteDirectoRoute,
  AppTrabajosDeProveedorRoute: AppTrabajosDeProveedorRoute,
  AppUsuariosIdRoute: AppUsuariosIdRoute,
  AppAgendaIndexRoute: AppAgendaIndexRoute,
  AppAuditoriaIndexRoute: AppAuditoriaIndexRoute,
  AppAusenciasIndexRoute: AppAusenciasIndexRoute,
  AppCalendarioIndexRoute: AppCalendarioIndexRoute,
  AppCatalogosIndexRoute: AppCatalogosIndexRoute,
  AppContratosIndexRoute: AppContratosIndexRoute,
  AppCotizacionesIndexRoute: AppCotizacionesIndexRoute,
  AppDocumentosIndexRoute: AppDocumentosIndexRoute,
  AppEntregablesIndexRoute: AppEntregablesIndexRoute,
  AppHorasExtraIndexRoute: AppHorasExtraIndexRoute,
  AppModulosIndexRoute: AppModulosIndexRoute,
  AppParametrosIndexRoute: AppParametrosIndexRoute,
  AppProgramacionIndexRoute: AppProgramacionIndexRoute,
  AppProspectosIndexRoute: AppProspectosIndexRoute,
  AppProveedoresIndexRoute: AppProveedoresIndexRoute,
  AppReportesIndexRoute: AppReportesIndexRoute,
  AppReunionesIndexRoute: AppReunionesIndexRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
  AppSeguimientoIndexRoute: AppSeguimientoIndexRoute,
  AppTareasIndexRoute: AppTareasIndexRoute,
  AppTrabajosIndexRoute: AppTrabajosIndexRoute,
  AppUsuariosIndexRoute: AppUsuariosIndexRoute,
  AppProspectosIdConvertirRoute: AppProspectosIdConvertirRoute,
  AppProspectosIdEditarRoute: AppProspectosIdEditarRoute,
  AppProspectosIdIndexRoute: AppProspectosIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ImprimirRouteChildren {
  ImprimirContratoIdRoute: typeof ImprimirContratoIdRoute
  ImprimirCotizacionIdRoute: typeof ImprimirCotizacionIdRoute
  ImprimirReciboIdRoute: typeof ImprimirReciboIdRoute
}

const ImprimirRouteChildren: ImprimirRouteChildren = {
  ImprimirContratoIdRoute: ImprimirContratoIdRoute,
  ImprimirCotizacionIdRoute: ImprimirCotizacionIdRoute,
  ImprimirReciboIdRoute: ImprimirReciboIdRoute,
}

const ImprimirRouteWithChildren = ImprimirRoute._addFileChildren(
  ImprimirRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ImprimirRoute: ImprimirRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
